;;; cursory-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cursory.el

(autoload 'cursory-set-preset "cursory" "\
Set cursor preset associated with STYLE.

STYLE is a symbol that represents the car of a list in
`cursory-presets'.

With optional LOCAL as a prefix argument, set the
`cursory-presets' only for the current buffer.  This does not
cover the `blink-cursor-mode', which is always global.

Call `cursory-set-preset-hook' as a final step.

(fn STYLE &optional LOCAL)" t)
(autoload 'cursory-store-latest-preset "cursory" "\
Write latest cursor state to `cursory-latest-state-file'.
Can be assigned to `kill-emacs-hook'.")
(autoload 'cursory-restore-latest-preset "cursory" "\
Restore latest cursor style.")
(defvar cursory-mode nil "\
Non-nil if Cursory mode is enabled.
See the `cursory-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `cursory-mode'.")
(custom-autoload 'cursory-mode "cursory" nil)
(autoload 'cursory-mode "cursory" "\
Persist Cursory presets.

Arrange to store and restore the current Cursory preset when
closing and restarting Emacs.

This is a global minor mode.  If called interactively, toggle the
`Cursory mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='cursory-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "cursory" '("cursory-"))

;;; End of scraped data

(provide 'cursory-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cursory-autoloads.el ends here
